name: Docker Build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          submodules: 'true'

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx and create new builder
        uses: docker/setup-buildx-action@v2
        with:
          create: true
          driver: docker-container
          driver-opts: |
            image=moby/buildkit:master

      - name: Login to Aliyun ACR
        uses: aliyun/acr-login@v1
        with:
          login-server: crpi-mefcp83bif5rwsdn.cn-chengdu.personal.cr.aliyuncs.com
          region-id: cn-chengdu
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}

      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: .
          push: true
          # Specify the platforms you want to build for  
          # (ensure that QEMU supports all these architectures):
          platforms: linux/amd64,linux/amd64/v2,linux/amd64/v3,linux/arm64,linux/riscv64,linux/ppc64le,linux/s390x,linux/386,linux/mips64le,linux/mips64,linux/loong64,linux/arm/v7,linux/arm/v6
          tags: |
            crpi-mefcp83bif5rwsdn.cn-chengdu.personal.cr.aliyuncs.com/lm379/alist-strm:latest
