name: actions

on: [push, pull_request] 

jobs:
  build_docker:
    if: ${{ github.ref == 'refs/heads/main' }} 
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    
    # 设置跨平台构建环境
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v2
    
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
      with:
        driver-opts: |
          image=moby/buildkit:master
    
    - name: Login to Aliyun Container Registry (ACR)
      uses: aliyun/acr-login@v1
      with:
        login-server: crpi-mefcp83bif5rwsdn.cn-chengdu.personal.cr.aliyuncs.com 
        region-id: cn-chengdu 
        username: "${{ secrets.REGISTRY_USERNAME }}"
        password: "${{ secrets.REGISTRY_PASSWORD }}"
    
    - name: Build and Push Multi-arch Docker Image
      env:
        IMAGE_TAG: latest
      run: |
        docker buildx build \
          --platform linux/amd64,linux/arm64 \
          -t crpi-mefcp83bif5rwsdn.cn-chengdu.personal.cr.aliyuncs.com/lm379/alist-strm:$IMAGE_TAG \
          --push \
          .
